### ISSUE TITLE
attacks/examples/explore1.py not terminating

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#44]
When running attacks/examples/explore1.py, it does not terminate. The last printed message was:

ERROR: Failed to remove cache DB cacheDBs/exampleExplore2.db

I notice, however, that no such .db file exists. Rather, the name of the .db file is `explore1.py.diffix.latest.banking.accounts.db`. Maybe this is related to the error?

On the assumption that this is related to the recent upgrade of caching, will assign this to Ali  ;)

**Comment by frzmohammadali** [comment]
fixes for both termination and "failed to remove cache DB" issues has been addressed in version 2.3.3 (current) of the "gda-score-code" package.

issue log:
program termination signal handling does not work ideally at the moment but implemented to its best possible extend. (some delay should be acceptable)

"failed to remove cache DB" error was due to usage of class level variable instead of instance level variable mistakenly in the code which is now fixed.
